/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;
import com.sun.glass.events.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Abdul Aziz
 */
public class BranchMgmtJPanel extends javax.swing.JPanel {

    private SSBank parent;
    /**
     * Creates new form BranchMgmtJPanel
     */
    public BranchMgmtJPanel() {
        initComponents();
    }
    public void setParent(SSBank parent)
    {
        this.parent=parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        bnameLabel = new javax.swing.JLabel();
        bcityLabel = new javax.swing.JLabel();
        bbalLabel = new javax.swing.JLabel();
        bnameTextField = new javax.swing.JTextField();
        bcityTextField = new javax.swing.JTextField();
        bbalTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bnameLabel1 = new javax.swing.JLabel();
        bcityLabel1 = new javax.swing.JLabel();
        bbalLabel1 = new javax.swing.JLabel();
        mbnameTextField = new javax.swing.JTextField();
        mbcityTextField = new javax.swing.JTextField();
        mbbalTextField = new javax.swing.JTextField();
        modifyButton = new javax.swing.JButton();
        bidLabel = new javax.swing.JLabel();
        bidTextField = new javax.swing.JTextField();
        selectlbidButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backButton = new javax.swing.JButton();

        bnameLabel.setText("Branch Name:");

        bcityLabel.setText("Branch City:");

        bbalLabel.setText("Branch Balance:");

        bbalTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bbalTextFieldKeyTyped(evt);
            }
        });

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bnameLabel)
                            .addComponent(bcityLabel)
                            .addComponent(bbalLabel))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bbalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(bcityTextField)
                            .addComponent(bnameTextField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(addButton)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnameLabel)
                    .addComponent(bnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bcityLabel)
                    .addComponent(bcityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbalLabel)
                    .addComponent(bbalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(addButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Branch", jPanel1);

        bnameLabel1.setText("Branch Name:");

        bcityLabel1.setText("Branch City:");

        bbalLabel1.setText("Branch Balance:");

        mbbalTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mbbalTextFieldKeyTyped(evt);
            }
        });

        modifyButton.setText("Modify Branch");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        bidLabel.setText("Branch ID:");

        bidTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bidTextFieldKeyTyped(evt);
            }
        });

        selectlbidButton.setText("Select");
        selectlbidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectlbidButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Branch");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bnameLabel1)
                    .addComponent(bcityLabel1)
                    .addComponent(bbalLabel1)
                    .addComponent(bidLabel))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mbbalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(mbcityTextField)
                    .addComponent(mbnameTextField)
                    .addComponent(bidTextField))
                .addGap(18, 18, 18)
                .addComponent(selectlbidButton)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modifyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(136, 136, 136))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bidLabel)
                    .addComponent(bidTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectlbidButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnameLabel1)
                    .addComponent(mbnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bcityLabel1)
                    .addComponent(mbcityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbalLabel1)
                    .addComponent(mbbalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(modifyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Modify Branch", jPanel2);

        jLabel1.setText("Branch Name:");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search Branch", jPanel3);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        parent.changeCard("card3");     // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        String bname="%"+jTextField1.getText()+"%";
        String query="{CALL SEARCHBRANCH(?)}";
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/banking?zeroDateTimeBehavior=convertToNull","root","");
        CallableStatement cstmt=conn.prepareCall(query);
        cstmt.setString(1, bname);
        ResultSet rs=cstmt.executeQuery();
        ResultSetTableModel1 model=new ResultSetTableModel1(rs);
        jTable1.setModel(model);
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(parent,ex.getMessage());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        try{
            String bname=bnameTextField.getText();
            String bcity=bcityTextField.getText();
            int bbal=Integer.parseInt(bbalTextField.getText());
            bnameTextField.setText("");
            bcityTextField.setText("");
            bbalTextField.setText("");
            if(bname==""||bcity==""||bbal<100000)
            {
                JOptionPane.showMessageDialog(parent,"Branch name or city cannot be null, balance must be greater than 100000");
                return;
            }
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/banking?zeroDateTimeBehavior=convertToNull","root","");
            String query="{CALL ADDBRANCH(?,?,?)}";
            CallableStatement cstmt=conn.prepareCall(query);
            cstmt.setString(1, bname);
            cstmt.setString(2, bcity);
            cstmt.setInt(3, bbal);
            ResultSet rs=cstmt.executeQuery();
            if(rs.next())
                JOptionPane.showMessageDialog(parent,"Branch Inserted with ID: "+rs.getInt(1));
            else
            {
                JOptionPane.showMessageDialog(parent,"Something went wrong");
            }
            cstmt.close();
            conn.close();
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(parent,ex.getMessage());
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void bbalTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bbalTextFieldKeyTyped
        // TODO add your handling code here:
        char key=evt.getKeyChar();
        if(!Character.isDigit(key)||key==KeyEvent.VK_BACKSPACE||key==KeyEvent.VK_DELETE)
            evt.consume();
    }//GEN-LAST:event_bbalTextFieldKeyTyped

    private void selectlbidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectlbidButtonActionPerformed
        // TODO add your handling code here:
        if(bidTextField.getText()=="")
            return;
        int bid=Integer.parseInt(bidTextField.getText());
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/banking?zeroDateTimeBehavior=convertToNull","root","");
        Statement stmt=conn.createStatement();
        ResultSet rs=stmt.executeQuery("SELECT name,city,balance FROM branch WHERE id="+bid);
        if(rs.next())
        {
            mbnameTextField.setText(rs.getString(1));
            mbcityTextField.setText(rs.getString(2));
            mbbalTextField.setText(Integer.toString(rs.getInt(3)));
        }
        else
        {
            JOptionPane.showMessageDialog(parent,"Branch with id "+bid+" does not exist");
            mbnameTextField.setText("");
            mbcityTextField.setText("");
            mbbalTextField.setText("");
        }
        stmt.close();
        conn.close();
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(parent,ex.getMessage());
        }
    }//GEN-LAST:event_selectlbidButtonActionPerformed

    private void bidTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bidTextFieldKeyTyped
        // TODO add your handling code here:
        char key=evt.getKeyChar();
        if(!Character.isDigit(key)||key==KeyEvent.VK_BACKSPACE||key==KeyEvent.VK_DELETE)
            evt.consume();
    }//GEN-LAST:event_bidTextFieldKeyTyped

    private void mbbalTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mbbalTextFieldKeyTyped
        // TODO add your handling code here:
        char key=evt.getKeyChar();
        if(!Character.isDigit(key)||key==KeyEvent.VK_BACKSPACE||key==KeyEvent.VK_DELETE)
            evt.consume();
    }//GEN-LAST:event_mbbalTextFieldKeyTyped

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        if(bidTextField.getText()=="" || mbnameTextField.getText()=="" ||mbcityTextField.getText()==""||mbbalTextField.getText()=="")
            return;
        int bid=Integer.parseInt(bidTextField.getText());
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/banking?zeroDateTimeBehavior=convertToNull","root","");
        Statement stmt=conn.createStatement();
        ResultSet rs=stmt.executeQuery("SELECT count(*) FROM branch WHERE id="+bid);
        rs.next();
        if(rs.getInt(1)<1)
        {
            JOptionPane.showMessageDialog(parent,"Branch with id "+bid+" does not exist");
            return;
        }
        String query="{CALL MODIFYBRANCH(?,?,?,?)}";
        CallableStatement cstmt=conn.prepareCall(query);
        cstmt.setInt(1, bid);
        cstmt.setString(2,mbnameTextField.getText());
        cstmt.setString(3,mbcityTextField.getText());
        cstmt.setInt(4,Integer.parseInt(mbbalTextField.getText()));
        cstmt.executeQuery();
        JOptionPane.showMessageDialog(parent,"Updated Branch successfully");
        stmt.close();
        cstmt.close();
        conn.close();
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(parent,ex.getMessage());
        }
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        if(bidTextField.getText()=="")
            return;
        int bid=Integer.parseInt(bidTextField.getText());
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/banking?zeroDateTimeBehavior=convertToNull","root","");
        Statement stmt=conn.createStatement();
        ResultSet rs=stmt.executeQuery("SELECT count(*) FROM branch WHERE id="+bid);
        rs.next();
        if(rs.getInt(1)<1)
        {
            JOptionPane.showMessageDialog(parent,"Branch with id "+bid+" does not exist");
            return;
        }
        stmt.executeUpdate("DELETE FROM branch WHERE id="+bid);
        JOptionPane.showMessageDialog(parent,"Deleted Branch successfully");
        stmt.close();
        conn.close();
        }catch(Exception ex)
        {
            JOptionPane.showMessageDialog(parent,ex.getMessage());
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bbalLabel;
    private javax.swing.JLabel bbalLabel1;
    private javax.swing.JTextField bbalTextField;
    private javax.swing.JLabel bcityLabel;
    private javax.swing.JLabel bcityLabel1;
    private javax.swing.JTextField bcityTextField;
    private javax.swing.JLabel bidLabel;
    private javax.swing.JTextField bidTextField;
    private javax.swing.JLabel bnameLabel;
    private javax.swing.JLabel bnameLabel1;
    private javax.swing.JTextField bnameTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mbbalTextField;
    private javax.swing.JTextField mbcityTextField;
    private javax.swing.JTextField mbnameTextField;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton selectlbidButton;
    // End of variables declaration//GEN-END:variables
}
