/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

/**
 *
 * @author Abdul Aziz
 */
public class EActionPanel extends javax.swing.JPanel {

    /**
     * Creates new form EActionPanel
     */
    public EActionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        addBranchButton = new javax.swing.JButton();
        addEmpButton = new javax.swing.JButton();
        runQueryButton = new javax.swing.JButton();
        searchCustButton = new javax.swing.JButton();
        addCustButton = new javax.swing.JButton();
        addAccButton = new javax.swing.JButton();
        modEmpButton = new javax.swing.JButton();
        modCustButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        addBranchButton.setText("Add Branch");
        addBranchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBranchButtonActionPerformed(evt);
            }
        });
        add(addBranchButton, new java.awt.GridBagConstraints());

        addEmpButton.setText("Add Employee");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(addEmpButton, gridBagConstraints);

        runQueryButton.setText("Run Query");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(runQueryButton, gridBagConstraints);

        searchCustButton.setText("Search Customers");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(searchCustButton, gridBagConstraints);

        addCustButton.setText("Add Customer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(addCustButton, gridBagConstraints);

        addAccButton.setText("Add Account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(addAccButton, gridBagConstraints);

        modEmpButton.setText("Modify Employee");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(modEmpButton, gridBagConstraints);

        modCustButton.setText("Modify Customer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(modCustButton, gridBagConstraints);

        jButton1.setText("Modify Branch");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(jButton1, gridBagConstraints);

        jButton2.setText("Modify Account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        add(jButton2, gridBagConstraints);

        jButton3.setText("Search Employee");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(jButton3, gridBagConstraints);

        jButton4.setText("Deposit/Withdraw");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(jButton4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void addBranchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBranchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBranchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAccButton;
    private javax.swing.JButton addBranchButton;
    private javax.swing.JButton addCustButton;
    private javax.swing.JButton addEmpButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton modCustButton;
    private javax.swing.JButton modEmpButton;
    private javax.swing.JButton runQueryButton;
    private javax.swing.JButton searchCustButton;
    // End of variables declaration//GEN-END:variables
}
